"""add_performance_indexes

Revision ID: 14e3312c2b59
Revises: 73cbf159a7c6
Create Date: 2026-04-02 14:15:06.652085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e3312c2b59'
down_revision: Union[str, None] = '73cbf159a7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artworks_created_at'), 'artworks', ['created_at'], unique=False)
    op.create_index(op.f('ix_artworks_status'), 'artworks', ['status'], unique=False)
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_index(op.f('ix_artworks_status'), table_name='artworks')
    op.drop_index(op.f('ix_artworks_created_at'), table_name='artworks')
    # ### end Alembic commands ###
