"""add_donation_certificate_fields

Revision ID: 73cbf159a7c6
Revises: 7e1969777e95
Create Date: 2026-04-01 11:29:44.029544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cbf159a7c6'
down_revision: Union[str, None] = '7e1969777e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('certificate_no', sa.String(length=100), nullable=True))
    op.add_column('donations', sa.Column('certificate_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_donations_certificate_no'), 'donations', ['certificate_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_certificate_no'), table_name='donations')
    op.drop_column('donations', 'certificate_url')
    op.drop_column('donations', 'certificate_no')
    # ### end Alembic commands ###
