"""refinement_for_iteration_3

Revision ID: 7e1969777e95
Revises: 42c9f6e6d8d0
Create Date: 2026-04-01 09:41:15.994913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1969777e95'
down_revision: Union[str, None] = '42c9f6e6d8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_participants', sa.Column('guardian_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_child_participants_guardian_user_id'), 'child_participants', ['guardian_user_id'], unique=False)
    op.create_foreign_key(None, 'child_participants', 'users', ['guardian_user_id'], ['id'])
    op.add_column('payment_transactions', sa.Column('payment_url', sa.String(length=500), nullable=True))
    op.add_column('payment_transactions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('payment_transactions', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_payment_transactions_idempotency_key'), 'payment_transactions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_idempotency_key'), table_name='payment_transactions')
    op.drop_column('payment_transactions', 'idempotency_key')
    op.drop_column('payment_transactions', 'expires_at')
    op.drop_column('payment_transactions', 'payment_url')
    op.drop_constraint(None, 'child_participants', type_='foreignkey')
    op.drop_index(op.f('ix_child_participants_guardian_user_id'), table_name='child_participants')
    op.drop_column('child_participants', 'guardian_user_id')
    # ### end Alembic commands ###
