"""reconcile_schema_with_models

Revision ID: 864b87240722
Revises: 003
Create Date: 2026-03-30 08:11:00.772224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '864b87240722'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artworks', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'artworks', 'child_participants', ['child_participant_id'], ['id'])
    op.add_column('audit_logs', sa.Column('user_name', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('resource', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('audit_logs', 'resource_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'created_at')
    op.create_foreign_key(None, 'donations', 'users', ['donor_user_id'], ['id'])
    op.create_foreign_key(None, 'donations', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_column('order_items', 'created_at')
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'carrier',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('orders', 'tracking_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('orders', 'logistics_events',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('order_no', table_name='orders')
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'currency')
    op.add_column('payment_transactions', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('payment_transactions', sa.Column('donation_id', sa.Integer(), nullable=True))
    op.add_column('payment_transactions', sa.Column('provider_transaction_id', sa.String(length=200), nullable=True))
    op.add_column('payment_transactions', sa.Column('raw_response', sa.JSON(), nullable=True))
    op.alter_column('payment_transactions', 'method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('wechat', 'alipay', 'stripe', 'paypal', name='payment_method'),
               existing_nullable=False)
    op.alter_column('payment_transactions', 'status',
               existing_type=mysql.ENUM('pending', 'completed', 'failed', 'refunded', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('pending', 'success', 'failed', 'refunded', name='payment_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index('transaction_id', table_name='payment_transactions')
    op.create_index(op.f('ix_payment_transactions_donation_id'), 'payment_transactions', ['donation_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_foreign_key(None, 'payment_transactions', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'payment_transactions', 'donations', ['donation_id'], ['id'])
    op.drop_column('payment_transactions', 'transaction_id')
    op.drop_column('payment_transactions', 'currency')
    op.drop_column('payment_transactions', 'payment_id')
    op.drop_column('payment_transactions', 'gateway_response')
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('products', 'currency',
               existing_type=mysql.ENUM('CNY', 'USD', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'CNY'"))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_foreign_key(None, 'products', 'clothing_intakes', ['source_clothing_intake_id'], ['id'])
    op.drop_column('products', 'updated_at')
    op.add_column('supply_chain_records', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('supply_chain_records', sa.Column('certified', sa.Boolean(), nullable=False))
    op.add_column('supply_chain_records', sa.Column('cert_image_url', sa.String(length=500), nullable=True))
    op.alter_column('supply_chain_records', 'stage',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Enum('material_sourcing', 'processing', 'manufacturing', 'quality_check', 'shipping', name='supply_chain_stage'),
               existing_nullable=False)
    op.alter_column('supply_chain_records', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=300),
               nullable=True)
    op.alter_column('supply_chain_records', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('ix_supply_chain_records_artwork_id', table_name='supply_chain_records')
    op.create_index(op.f('ix_supply_chain_records_product_id'), 'supply_chain_records', ['product_id'], unique=False)
    op.create_foreign_key(None, 'supply_chain_records', 'products', ['product_id'], ['id'])
    op.drop_column('supply_chain_records', 'artwork_id')
    op.drop_column('supply_chain_records', 'verified')
    op.drop_column('supply_chain_records', 'verifier_name')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.add_column('supply_chain_records', sa.Column('verifier_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('supply_chain_records', sa.Column('verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('supply_chain_records', sa.Column('artwork_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'supply_chain_records', type_='foreignkey')
    op.drop_index(op.f('ix_supply_chain_records_product_id'), table_name='supply_chain_records')
    op.create_index('ix_supply_chain_records_artwork_id', 'supply_chain_records', ['artwork_id'], unique=False)
    op.alter_column('supply_chain_records', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('supply_chain_records', 'location',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)
    op.alter_column('supply_chain_records', 'stage',
               existing_type=sa.Enum('material_sourcing', 'processing', 'manufacturing', 'quality_check', 'shipping', name='supply_chain_stage'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_column('supply_chain_records', 'cert_image_url')
    op.drop_column('supply_chain_records', 'certified')
    op.drop_column('supply_chain_records', 'product_id')
    op.add_column('products', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.alter_column('products', 'currency',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('CNY', 'USD', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('products', 'name',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
    op.drop_column('products', 'category')
    op.add_column('payment_transactions', sa.Column('gateway_response', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('payment_transactions', sa.Column('payment_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('payment_transactions', sa.Column('currency', mysql.ENUM('CNY', 'USD', collation='utf8mb4_unicode_ci'), server_default=sa.text("'CNY'"), nullable=False))
    op.add_column('payment_transactions', sa.Column('transaction_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_donation_id'), table_name='payment_transactions')
    op.create_index('transaction_id', 'payment_transactions', ['transaction_id'], unique=True)
    op.alter_column('payment_transactions', 'status',
               existing_type=sa.Enum('pending', 'success', 'failed', 'refunded', name='payment_status'),
               type_=mysql.ENUM('pending', 'completed', 'failed', 'refunded', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('payment_transactions', 'method',
               existing_type=sa.Enum('wechat', 'alipay', 'stripe', 'paypal', name='payment_method'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.drop_column('payment_transactions', 'raw_response')
    op.drop_column('payment_transactions', 'provider_transaction_id')
    op.drop_column('payment_transactions', 'donation_id')
    op.drop_column('payment_transactions', 'order_id')
    op.add_column('orders', sa.Column('currency', mysql.ENUM('CNY', 'USD', collation='utf8mb4_unicode_ci'), server_default=sa.text("'CNY'"), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.create_index('order_no', 'orders', ['order_no'], unique=True)
    op.alter_column('orders', 'logistics_events',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('orders', 'tracking_number',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('orders', 'carrier',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('order_items', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.add_column('audit_logs', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'resource')
    op.drop_column('audit_logs', 'user_name')
    op.drop_constraint(None, 'artworks', type_='foreignkey')
    op.drop_constraint(None, 'artworks', type_='foreignkey')
    # ### end Alembic commands ###
