/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'paper': '#F5F0E8',
        'aged-stock': '#EDE6D6',
        'warm-gray': '#D4CFC4',
        'ink': '#1A1A16',
        'ink-faded': '#4A4540',
        'ink-light': '#6B665C',
        'sepia-mid': '#5C4D3D',
        'sepia-dark': '#3D3228',
        'sepia-light': '#8B7B66',
        'rust': '#8B3A2A',
        'rust-light': '#A85A4A',
        'rust-dark': '#6B2A1A',
        'archive-brown': '#5C4033',
        'pale-gold': '#C4A45A',
        'pale-gold-light': '#D4BC7A',
        'sepia-on-dark': '#B5A595',
        'muted-gray': '#B8B2A7',
        'cream': '#FAF6EE',
        'eco-green': '#5a7a5a',
        'sage': '#3F4F45',
        'sage-light': '#5A6B5F',
        'sage-lighter': '#7A8B7E',
        'sage-muted': '#95A398',
        'sage-pale': '#C8D1CA',
        'sage-dark': '#2D3B33',
        'editorial-red': '#C41E3A',
        'editorial-navy': '#1C2841',
        'editorial-olive': '#4A5240',
        'editorial-burgundy': '#6B2D3D',
        'success': '#3D5A3D',
        'error': '#8B3A2A',
        'warning': '#A68A3D',
        'info': '#3D4A5C',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'Georgia', 'serif'],
        'body': ['"IBM Plex Mono"', '"Courier New"', 'monospace'],
        'ui': ['Inter', '"Source Sans Pro"', 'sans-serif'],
      },
      fontSize: {
        'hero': 'clamp(64px, 10vw, 120px)',
        'h1': 'clamp(40px, 6vw, 72px)',
        'h2': 'clamp(28px, 4vw, 48px)',
        'h3': 'clamp(20px, 2.5vw, 32px)',
        'overline': '10px',
        'label': '11px',
        'caption': '12px',
        'body-sm': '14px',
        'body': '16px',
      },
    },
  },
  plugins: [],
};
