import morandiPlugin from './src/styles/morandi-tailwind-plugin.js';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Editorial palette — CSS variables that respond to [data-theme] on <html>
        // Using [data-theme] selectors to ensure Tailwind picks up dynamic values
        'paper': 'var(--color-paper)',
        'aged-stock': 'var(--color-aged-stock)',
        'warm-gray': 'var(--color-warm-gray)',
        'ink': 'var(--color-ink)',
        'ink-faded': 'var(--color-ink-faded)',
        'ink-light': 'var(--color-ink-light)',
        'sepia-mid': 'var(--color-sepia-mid)',
        'sepia-dark': 'var(--color-sepia-dark)',
        'sepia-light': 'var(--color-sepia-light)',
        'sepia-on-dark': 'var(--color-sepia-on-dark)',
        'rust': 'var(--color-rust)',
        'rust-light': 'var(--color-rust-light)',
        'rust-dark': 'var(--color-rust-dark)',
        'archive-brown': 'var(--color-archive-brown)',
        'pale-gold': 'var(--color-pale-gold)',
        'pale-gold-light': 'var(--color-pale-gold-light)',
        'muted-gray': 'var(--color-muted-gray)',
        'cream': 'var(--color-cream)',
        'eco-green': 'var(--color-eco-green)',
        'sage': 'var(--color-sage)',
        'sage-light': 'var(--color-sage-light)',
        'sage-lighter': 'var(--color-sage-lighter)',
        'sage-muted': 'var(--color-sage-muted)',
        'sage-pale': 'var(--color-sage-pale)',
        'sage-dark': 'var(--color-sage-dark)',
        'editorial-red': 'var(--color-editorial-red)',
        'editorial-navy': 'var(--color-editorial-navy)',
        'editorial-olive': 'var(--color-editorial-olive)',
        'editorial-burgundy': 'var(--color-editorial-burgundy)',
        'success': 'var(--color-success)',
        'error': 'var(--color-error)',
        'warning': 'var(--color-warning)',
        'info': 'var(--color-info)',
        // Theme-aware colors — switch with data-theme
        'theme-bg': 'var(--theme-bg)',
        'theme-bg-elevated': 'var(--theme-bg-elevated)',
        'theme-bg-subtle': 'var(--theme-bg-subtle)',
        'theme-panel': 'var(--theme-panel)',
        'theme-text': 'var(--theme-text)',
        'theme-text-muted': 'var(--theme-text-muted)',
        'theme-border': 'var(--theme-border)',
        'theme-accent': 'var(--theme-accent)',
        'theme-rust': 'var(--theme-rust)',
      },
      // Ensure background-color and text-color utilities use CSS variables dynamically
      backgroundColor: {
        'paper': 'var(--color-paper)',
        'aged-stock': 'var(--color-aged-stock)',
        'warm-gray': 'var(--color-warm-gray)',
        'muted-gray': 'var(--color-muted-gray)',
        'cream': 'var(--color-cream)',
        'eco-green': 'var(--color-eco-green)',
        'theme-bg': 'var(--theme-bg)',
        'theme-bg-elevated': 'var(--theme-bg-elevated)',
        'theme-bg-subtle': 'var(--theme-bg-subtle)',
        'theme-panel': 'var(--theme-panel)',
      },
      textColor: {
        'paper': 'var(--color-paper)',
        'ink': 'var(--color-ink)',
        'ink-faded': 'var(--color-ink-faded)',
        'ink-light': 'var(--color-ink-light)',
        'sepia-mid': 'var(--color-sepia-mid)',
        'sepia-dark': 'var(--color-sepia-dark)',
        'sepia-light': 'var(--color-sepia-light)',
        'rust': 'var(--color-rust)',
        'rust-light': 'var(--color-rust-light)',
        'rust-dark': 'var(--color-rust-dark)',
        'theme-text': 'var(--theme-text)',
        'theme-text-muted': 'var(--theme-text-muted)',
      },
      borderColor: {
        'warm-gray': 'var(--color-warm-gray)',
        'muted-gray': 'var(--color-muted-gray)',
        'sepia-mid': 'var(--color-sepia-mid)',
        'sepia-dark': 'var(--color-sepia-dark)',
        'sepia-light': 'var(--color-sepia-light)',
        'rust': 'var(--color-rust)',
        'theme-border': 'var(--theme-border)',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'Georgia', 'serif'],
        'body': ['"IBM Plex Mono"', '"Courier New"', 'monospace'],
        'ui': ['Inter', '"Source Sans Pro"', 'sans-serif'],
      },
      fontSize: {
        'hero': 'clamp(64px, 10vw, 120px)',
        'h1': 'clamp(40px, 6vw, 72px)',
        'h2': 'clamp(28px, 4vw, 48px)',
        'h3': 'clamp(20px, 2.5vw, 32px)',
        'overline': '10px',
        'label': '11px',
        'caption': '12px',
        'body-sm': '14px',
        'body': '16px',
      },
    },
  },
  plugins: [morandiPlugin],
};
